<?php

return [
    'categories' => [
        [
            'key' => 'core_financial',
            'title' => 'Core Financial Reports',
            'icon' => 'fa-solid fa-file-invoice',
            'reports' => [
                ['slug' => 'trial_balance', 'title' => 'Trial Balance'],
                ['slug' => 'profit_and_loss', 'title' => 'Profit & Loss Account'],
                ['slug' => 'balance_sheet', 'title' => 'Balance Sheet'],
                ['slug' => 'cash_flow_statement', 'title' => 'Cash Flow Statement'],
                ['slug' => 'general_ledger', 'title' => 'General Ledger'],
                ['slug' => 'chart_of_accounts_report', 'title' => 'Chart of Accounts Report'],
            ],
        ],
        [
            'key' => 'balance_closing',
            'title' => 'Account Balance & Closing',
            'icon' => 'fa-solid fa-scale-balanced',
            'reports' => [
                ['slug' => 'account_balance_statement', 'title' => 'Account Balance Statement'],
                ['slug' => 'party_ledger_balance', 'title' => 'Party-wise Ledger Balance'],
                ['slug' => 'monthly_closing_report', 'title' => 'Monthly Closing Report'],
                ['slug' => 'year_end_closing_report', 'title' => 'Year End Closing Report'],
                ['slug' => 'opening_vs_closing_comparison', 'title' => 'Opening vs Closing Comparison'],
                ['slug' => 'suspense_account_report', 'title' => 'Suspense Account Report'],
            ],
        ],
        [
            'key' => 'vat_tax',
            'title' => 'VAT / TAX Reports',
            'icon' => 'fa-solid fa-percent',
            'reports' => [
                ['slug' => 'vat_sales_register', 'title' => 'VAT Sales Register'],
                ['slug' => 'vat_purchase_register', 'title' => 'VAT Purchase Register'],
                ['slug' => 'vat_payable_report', 'title' => 'VAT Payable Report'],
                ['slug' => 'vat_input_credit_report', 'title' => 'VAT Input Credit Report'],
                ['slug' => 'vat_output_report', 'title' => 'VAT Output Report'],
                ['slug' => 'monthly_vat_return_summary', 'title' => 'Monthly VAT Return Summary'],
                ['slug' => 'tds_deduction_report', 'title' => 'TDS Deduction Report'],
                ['slug' => 'tds_payable_paid_statement', 'title' => 'TDS Payable & Paid Statement'],
            ],
        ],
        [
            'key' => 'purchase',
            'title' => 'Purchase & Procurement',
            'icon' => 'fa-solid fa-cart-shopping',
            'reports' => [
                ['slug' => 'purchase_register', 'title' => 'Purchase Register'],
                ['slug' => 'raw_material_purchase_report', 'title' => 'Raw Material Purchase'],
                ['slug' => 'fabric_purchase_report', 'title' => 'Fabric Purchase'],
                ['slug' => 'accessories_purchase_report', 'title' => 'Accessories Purchase'],
                ['slug' => 'local_purchase_report', 'title' => 'Local Purchase'],
                ['slug' => 'import_purchase_report', 'title' => 'Import Purchase'],
                ['slug' => 'supplier_wise_purchase_summary', 'title' => 'Supplier-wise Purchase Summary'],
                ['slug' => 'po_status_report', 'title' => 'PO Status Report'],
                ['slug' => 'grn_report', 'title' => 'GRN Report'],
            ],
        ],
        [
            'key' => 'export_sales',
            'title' => 'Export & Sales (RMG)',
            'icon' => 'fa-solid fa-shirt',
            'reports' => [
                ['slug' => 'export_sales_register', 'title' => 'Export Sales Register'],
                ['slug' => 'invoice_wise_export_report', 'title' => 'Invoice-wise Export'],
                ['slug' => 'buyer_wise_sales_report', 'title' => 'Buyer-wise Sales'],
                ['slug' => 'country_wise_export_report', 'title' => 'Country-wise Export'],
                ['slug' => 'order_wise_shipment_report', 'title' => 'Order-wise Shipment'],
                ['slug' => 'fob_value_report', 'title' => 'FOB Value Report'],
                ['slug' => 'cif_fob_adjustment_report', 'title' => 'CIF/FOB Adjustment'],
                ['slug' => 'export_realization_report', 'title' => 'Export Realization'],
                ['slug' => 'sales_return_report', 'title' => 'Sales Return'],
            ],
        ],
        [
            'key' => 'lc_banking',
            'title' => 'LC & Banking',
            'icon' => 'fa-solid fa-ship',
            'reports' => [
                ['slug' => 'lc_opening_report', 'title' => 'LC Opening Report'],
                ['slug' => 'lc_utilization_report', 'title' => 'LC Utilization Report'],
                ['slug' => 'back_to_back_lc_report', 'title' => 'Back-to-Back LC Report'],
                ['slug' => 'lc_margin_report', 'title' => 'LC Margin Report'],
                ['slug' => 'bank_payment_receipt_report', 'title' => 'Bank Payment & Receipt'],
                ['slug' => 'export_proceeds_realization_report', 'title' => 'Export Proceeds Realization'],
                ['slug' => 'btb_payment_status', 'title' => 'BTB Payment Status'],
            ],
        ],
        [
            'key' => 'production_costing',
            'title' => 'Production & Costing',
            'icon' => 'fa-solid fa-industry',
            'reports' => [
                ['slug' => 'production_cost_sheet', 'title' => 'Production Cost Sheet'],
                ['slug' => 'style_wise_costing_report', 'title' => 'Style-wise Costing'],
                ['slug' => 'cm_cost_report', 'title' => 'CM Cost Report'],
                ['slug' => 'fob_cost_breakdown', 'title' => 'FOB Cost Breakdown'],
                ['slug' => 'wip_report', 'title' => 'WIP Report'],
                ['slug' => 'finished_goods_report', 'title' => 'Finished Goods'],
                ['slug' => 'order_cost_vs_profit_report', 'title' => 'Order Cost vs Profit'],
            ],
        ],
        [
            'key' => 'payroll_hr',
            'title' => 'Payroll & HR Financial',
            'icon' => 'fa-solid fa-users',
            'reports' => [
                ['slug' => 'salary_sheet', 'title' => 'Salary Sheet'],
                ['slug' => 'overtime_report', 'title' => 'Overtime Report'],
                ['slug' => 'attendance_salary_integration_report', 'title' => 'Attendance Salary Integration'],
                ['slug' => 'worker_wise_cost_report', 'title' => 'Worker-wise Cost'],
                ['slug' => 'bonus_report', 'title' => 'Bonus Report'],
                ['slug' => 'pf_gratuity_report', 'title' => 'PF / Gratuity Report'],
            ],
        ],
        [
            'key' => 'inventory_store',
            'title' => 'Inventory / Store',
            'icon' => 'fa-solid fa-boxes-stacked',
            'reports' => [
                ['slug' => 'raw_material_stock_report', 'title' => 'Raw Material Stock'],
                ['slug' => 'fabric_stock_report', 'title' => 'Fabric Stock'],
                ['slug' => 'accessories_stock_report', 'title' => 'Accessories Stock'],
                ['slug' => 'issue_return_report', 'title' => 'Issue & Return'],
                ['slug' => 'store_ledger', 'title' => 'Store Ledger'],
                ['slug' => 'stock_valuation_report', 'title' => 'Stock Valuation'],
            ],
        ],
        [
            'key' => 'bank_cash',
            'title' => 'Bank & Cash',
            'icon' => 'fa-solid fa-building-columns',
            'reports' => [
                ['slug' => 'cash_book_report', 'title' => 'Cash Book'],
                ['slug' => 'bank_book_report', 'title' => 'Bank Book'],
                ['slug' => 'bank_reconciliation_statement', 'title' => 'Bank Reconciliation (BRS)'],
                ['slug' => 'daily_cash_position_report', 'title' => 'Daily Cash Position'],
                ['slug' => 'payment_voucher_report', 'title' => 'Payment Voucher Report'],
                ['slug' => 'receipt_voucher_report', 'title' => 'Receipt Voucher Report'],
            ],
        ],
        [
            'key' => 'management_audit',
            'title' => 'Management & Audit',
            'icon' => 'fa-solid fa-magnifying-glass-chart',
            'reports' => [
                ['slug' => 'aging_receivable', 'title' => 'Aging Report (Receivable)'],
                ['slug' => 'aging_payable', 'title' => 'Aging Report (Payable)'],
                ['slug' => 'export_receivable_aging', 'title' => 'Export Receivable Aging'],
                ['slug' => 'party_outstanding_report', 'title' => 'Party Outstanding'],
                ['slug' => 'audit_trail_report', 'title' => 'Audit Trail'],
                ['slug' => 'exception_missing_entry_report', 'title' => 'Exception / Missing Entry'],
                ['slug' => 'monthly_management_pack', 'title' => 'Monthly Management Pack'],
            ],
        ],
        [
            'key' => 'rmg_advanced',
            'title' => 'RMG Advanced Analytics',
            'icon' => 'fa-solid fa-chart-pie',
            'reports' => [
                ['slug' => 'order_booking_vs_shipment_tracking', 'title' => 'Order Booking vs Shipment'],
                ['slug' => 'style_profitability_report', 'title' => 'Style Profitability'],
                ['slug' => 'buyer_profit_contribution_report', 'title' => 'Buyer Profit Contribution'],
                ['slug' => 'shipment_delay_report', 'title' => 'Shipment Delay'],
                ['slug' => 'export_compliance_report', 'title' => 'Export Compliance'],
                ['slug' => 'duty_drawback_bond_utilization_report', 'title' => 'Duty Drawback / Bond'],
            ],
        ],
    ],
];
